### ISSUE TITLE
403 Forbidden - before you post here

### ISSUE THREAD

**Issue by nichan200** [RogueEdit/onlineRogueEditor#87]
![pkrogue](https://github.com/RogueEdit/onlineRogueEditor/assets/15617682/ae304ce4-42cf-4384-ac7c-9d8509520e8a)
As I saw that it no longer left the 1st option, I tried the second one and it doesn't work in version 1.7 of the application, this error occurs

**Comment by JulianStiebler** [comment]
403's are not directly on us - its when cloudlfare blocks access, for us unknown reason. Either they ban the headers or no idea. 

You should see a failback mechanism to refetch the data. Otherwise you can look in your "headerfile-public.json" and replace the user-agents in its list. This will make it so the tool will have new headers to choose from. You can ask chatGPT to give you some :)

**Comment by nichan200** [comment]
I tell you that I don't understand much about the subject, that's why I prefer to wait until I use version 1.2 since 1.5 still doesn't let me in due to the same old error.

**Comment by JulianStiebler** [comment]
Yeah v0.1.2 appears to work the whole time.

**Comment by Valsahn** [comment]
I tried the solution with ChatGPT but i only have the headerfile-save, not the public one you meant

I also edited it but still not working :(

**Comment by JulianStiebler** [comment]
@Valsahn yeah that seeding wasnt smart. It actually makes not much difference, further version up dont have it.
https://github.com/RogueEdit/onlineRogueEditor/releases/tag/v0.2... :'D lets hope it stays. I think we are just conflicting with cloudflare.
